### ISSUE TITLE
Handling network change

### ISSUE THREAD

**Issue by ropod7** [MetaMask/faq#7] opened 2016-12-06 22:31 UTC
Please, try to catch exception: "Error: PortDuplexStream - disconnected" on jump to Main<->Testnet.
Should be perfect if we may handle this jumps same as on jumps between accounts.

**Comment by flyswatter** [comment] 2016-12-06 23:32
I spent most of Monday on this, but it has been tricky to track down.  Hopefully @kumavis will be able to spend some time on this soon, as he wrote the related code.

Closing as a duplicate of #873.

**Closed by flyswatter** 2016-12-06 23:32 UTC
