### ISSUE TITLE
Import JSON file closes window on Firefox

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/faq#80] opened 2017-10-31 05:11 UTC
The workaround only works for chrome.

**Comment by Lionade** [comment] 2017-12-11 12:55
I have the same issue. Did you find any solution yet?

**Comment by longnd** [comment] 2017-12-17 09:55
I also have the same issue, click the Browse button to browse the json file, Firefox opens the file picker windows which close Metamask. It's really frustrating

**Comment by danfinlay** [comment] 2017-12-17 23:52
Duplicate of https://github.com/MetaMask/metamask-extension/issues/2722 which links to a workaround.

 Since this is a browser bug, there’s nothing we can do for this until we allow the ability to open MetaMask in a full tab for forms like this.

**Closed by danfinlay** 2017-12-17 23:52 UTC
