### ISSUE TITLE
Feature Request - Show Ethereum Tokens

### ISSUE THREAD

**Issue by mchl18** [MetaMask/faq#37] opened 2017-06-27 10:21 UTC
It would be nice to be able to add ethereum tokens, to see a balance of all tokens, like myetherwallet does.
I am currently quite busy but would consider a pull request for that, even though i havent worked with chrome extensions specifically.

**Comment by mchl18** [comment] 2017-06-27 10:22
I just realized i was in the wrong repo, please close

**Comment by flyswatter** [comment] 2017-06-27 15:43
Duplicate of https://github.com/MetaMask/metamask-plugin/issues/175
Partly merged already via https://github.com/MetaMask/metamask-plugin/pull/1603
Adding tokens added in https://github.com/MetaMask/metamask-plugin/pull/1620
Send token button added in https://github.com/MetaMask/metamask-plugin/pull/1634

**Closed by flyswatter** 2017-06-27 15:43 UTC

**Comment by flyswatter** [comment] 2017-06-27 15:45
Thanks for the feedback, we thrive on it, fortunately for you, this has been a very popular feature request for a long time, and we're finally caving to it. (I used to really think someone would make a dominant web UI for tokens, and while a few exist, using websites to manage tokens just never caught on with our users.)

You can in fact manage tokens with metamask today using a web dapp:
https://github.com/MetaMask/faq/blob/master/USERS.md#managing-tokens
